<div id="mana_comment_progress" class="dialog message mana_comment_status" style="display:none">
 <div id="loading"> <img src="[% interface | html %]/[% theme | html %]/img/spinner-small.gif" alt="" /> تقديم تعليق </div>
</div>
<div id="mana_comment_success" class="dialog message mana_comment_status" style="display:none">
 تم تقديم تعليقك </div>
<div id="mana_comment_failed" class="dialog alert mana_comment_status" style="display:none">
 لا يمكن تقديم تعليقك. يرجى إعادة المحاولة مرة أخرى. </div>