<!-- Cashup summary modal -->
<div class="modal printable" id="cashupSummaryModal" tabindex="-1" role="dialog" aria-labelledby="cashupSummaryLabel">
 <div class="modal-dialog" role="document">
 <div class="modal-content">
 <div class="modal-header">
 <button aria-label="إغلاق" class="closebtn" data-dismiss="modal" type="button"><span aria-hidden="true">&times;</span></button>
 <h4 class="modal-title" id="cashupSummaryLabel">ملخص الدفع النقدي</h4>
 </div>
 <div class="modal-body">
 <ul>
 <li>سجل نقدي: <span id="register_description"></span></li>
 <li>فترة: <span id="from_date"></span> إلى <span id="to_date"></span></li>
 </ul>
 <table>
 <thead>
 <tr>
 <th>نوع</th>
 <th>الإجمالي</th>
 </tr>
 </thead>
 <tbody>
 </tbody>
 <tfoot>
 </tfoot>
 </table>
 </div> <!-- /.modal-body -->
 <div class="modal-footer">
 <button type="button" class="btn btn-default" data-dismiss="modal">إغلاق</button>
 <button type="button" class="printModal btn btn-primary"><i class="fa fa-print"></i> طباعة</button>
 </div> <!-- /.modal-footer -->
 </div> <!-- /.modal-content -->
 </div> <!-- /.modal-dialog -->
</div> <!-- /#cashupSummaryModal -->
