<div id="ArticleRequestsDisclaimerText_notes" class="hint customization_note">
 سيتم عرض هذا المحتوى لمستخدم الأوباك قبل أن يتمكن من وضع طلب مقال. </div>

<div id="CatalogConcernHelp_notes"  class="hint customization_note">
 إدراج هذا المحتوى في النموذج الموضح في الأوباك عند قيام المستخدم بتقديم بلاغ بشكوى خاصة بالفهرس. </div>

<div id="CatalogConcernTemplate_notes"  class="hint customization_note">
 ملء نموذج شكوى الفهرس مسبقاً بهذا المحتوى كقالب لتقديم المستخدم. </div>

<div id="CookieConsentBar_notes"  class="hint customization_note">
 إدراج هذا المحتوى في تذييل الموافقة على ملف تعريف الارتباط والذي يتم عرضه في الأوباك عند تفعيل تفضيل النظام CookieConsent. </div>

<div id="CookieConsentPopup_notes"  class="hint customization_note">
 إدراج هذا المحتوى في الرسالة المنبثقة التي يتم عرضها في الأوباك عند تفعيل تفضيل النظام CookieConsent وقيان المستخدم بالنقر على عنصر القائمة "ملفات تعريف الارتباط الخاصة بك" في الرأس. </div>

<div id="ILLModuleCopyrightClearance_notes" class="hint customization_note">
 Adding content to this region will enable the copyright clearance stage in request creation. The content will appear on the OPAC during the process of placing an ILL request.
</div>

<div id="opaccredits_notes" class="hint customization_note">
 إدراج هذا المحتوى في تذييل جميع الصفحات في الأوباك. </div>

<div id="OpacCustomSearch_notes" class="hint customization_note">
 استبدال مربع البحث أعلى صفحات الأوباك بهذا المحتوى. </div>

<div id="opacheader_notes" class="hint customization_note">
 إدراج هذا المحتوى في رأس كل الصفحات في الأوباك. </div>

<div id="OpacLibraryInfo_notes" class="hint customization_note">
 إدراج هذا المحتوى في صفحة معلومات المكتبة في الأوباك. </div>

<div id="OpacLoginInstructions_notes" class="hint customization_note">
 عرض هذا المحتوى في نموذج تسجيل دخول الأوباك عندما لا يكون المستفيد مسجلاً للدخول. </div>

<div id="OpacMaintenanceNotice_notes" class="hint customization_note">
 عرض هذا المحتوى في الأوباك عندما يتم تفعيل تفضيل النظام OpacMaintenance. </div>

<div id="OpacMainUserBlock_notes" class="hint customization_note">
 عرض هذا المحتوى في العمود الخاص به في الصفحة الرئيسية للأوباك. </div>

<div id="OpacMoreSearches_notes" class="hint customization_note">
 إضافة عناصر إضافية إلى شريط التنقل الموجود أسفل نموذج البحث البسيط. </div>

<div id="OpacMySummaryNote_notes" class="hint customization_note">
 ملاحظة للعرض في صفحة ملخص المستفيد. تظهر هذه الملاحظة فقط إذا قام المستفيد بتسجيل الدخول. </div>

<div id="OpacNav_notes" class="hint customization_note">
 عرض هذا المحتوى في العمود الأيسر من الصفحة الرئيسية وحساب المستفيد في الأوباك (روابط التنقل بشكل عام). </div>

<div id="OpacNavBottom_notes" class="hint customization_note">
 عرض هذا المحتوى في العمود الأيسر من الصفحة الرئيسية وحساب المستفيد في الأوباك، بعد OpacNav، وقبل روابط حساب المستفيد إذا كانت متاحة. </div>

<div id="OpacNavRight_notes" class="hint customization_note">
 عرض هذا المحتوى في العمود الأيمن من الصفحة الرئيسية أدنى نموذج تسجيل الدخول الرئيسي. </div>

<div id="OPACResultsSidebar_notes" class="hint customization_note">
 عرض هذا المحتوى أدنى الفاست في نتائج بحث الأوباك. </div>

<div id="OpacSuggestionInstructions_notes" class="hint customization_note">
 عرض هذا المحتوى أعلى نموذج مقترحات الشراء في الأوباك. </div>

<div id="OpacSuppressionMessage_notes" class="hint customization_note">
 عرض الرسالة التالية في صفحة إعادة التوجيه للتسجيلات الببليوغرافية المحجوبة. يعتمد على تفضيلات النظام OpacSuppression وOpacSuppressionRedirect. </div>

<div id="PatronSelfRegistrationAdditionalInstructions_notes" class="hint customization_note">
 عرض المحتوى التالي في صفحة تأكيد التسجيل الذاتي للمستفيد. </div>

<div id="SCOMainUserBlock_notes" class="hint customization_note">
 عرض هذا المحتوى في شاشة الإعارة الذاتية المستندة إلى الويب. </div>

<div id="SelfCheckHelpMessage_notes" class="hint customization_note">
 عرض هذا المحتوى في صفحة المساعدة الخاصة بنظام الإعارة الذاتية المستندة إلى الويب. </div>

<div id="SelfCheckInMainUserBlock_notes" class="hint customization_note">
 عرض هذا المحتوى في شاشة الرد الذاتي. </div>

<div id="StaffAcquisitionsHome_notes" class="hint customization_note">
 عرض هذا المحتوى في الصفحة الرئيسية للمقتنيات في واجهة الموظفين. </div>

<div id="StaffAuthoritiesHome_notes" class="hint customization_note">
 عرض هذا المحتوى في الصفحة الرئيسية للاستنادات في واجهة الموظفين. </div>

<div id="StaffCataloguingHome_notes" class="hint customization_note">
 عرض هذا المحتوى في الصفحة الرئيسية للفهرسة في واجهة الموظفين. </div>

<div id="StaffListsHome_notes" class="hint customization_note">
 عرض هذا المحتوى في الصفحة الرئيسية للقوائم في واجهة الموظفين. </div>

<div id="StaffPatronsHome_notes" class="hint customization_note">
 عرض هذا المحتوى في الصفحة الرئيسية للمستفيدين في واجهة الموظفين. </div>

<div id="StaffPOSHome_notes" class="hint customization_note">
 عرض هذا المحتوى في الصفحة الرئيسية لنقطة البيع في واجهة الموظفين. </div>

<div id="StaffSerialsHome_notes" class="hint customization_note">
 عرض هذا المحتوى في الصفحة الرئيسية للدوريات في واجهة الموظفين. </div>
