<!-- ill-batch-table-strings.inc -->
<script>
    var ill_batch_add = _("إضافة دفعة جديدة");
    var ill_batch_update = _("تحديث الدفعة");
    var ill_batch_none = _("لا شيء");
    var ill_batch_retrieving_metadata = _("جاري استرداد الميتاداتا");
    var ill_batch_api_fail = _("غير قادر على استرداد تفاصيل الدفعة");
    var ill_batch_statuses_api_fail = _("غير قادر على استرداد حالات بالدفعة");
    var ill_batch_api_request_fail = _("غير قادر على إنشاء طلب محلي");
    var ill_batch_requests_api_fail = _("غير قادر على استرداد طلبات بالدفعة");
    var ill_batch_unknown = _("غير معروف");
    var ill_batch_doi = _("معرّف الكائن الرقمي");
    var ill_batch_pmid = _("معرف PubMed");
    var ill_populate_waiting = _("جاري الاسترداد...");
    var ill_populate_failed = _("فشل استرداد");
    var ill_button_remove = _("إزالة");
    var ill_batch_create_api_fail = _("غير قادر على إنشاء طلب بالدفعة");
    var ill_batch_update_api_fail = _("غير قادر على تحديث الطلب بالدفعة");
    var ill_batch_item_remove = _("هل أنت متأكد من أنك تريد إزالة هذه المادة من الدفعة؟");
    var ill_batch_create_cancel_button = _("إغلاق");
    var ill_batch_metadata_more = _("المزيد");
    var ill_batch_metadata_less = _("أقل");
    var ill_batch_available_via = _("متاح عبر");
    var ill_batch_metadata = {
        'doi': _("معرّف الكائن الرقمي"),
        'pmid': _("معرف PubMed"),
        'issn': _("تدمد"),
        'title': _("عنوان"),
        'year': _("عام"),
        'issue': _("عدد"),
        'pages': _("صفحات"),
        'publisher': _("الناشر"),
        'article_title': _("عنوان المقال"),
        'article_author': _("كاتب المقال"),
        'volume': _("مجلد")
    };
</script>
<!-- / ill-batch-table-strings.inc -->
