<!-- ill-list-table-strings.inc -->
<script>
    var ill_borrower_details = _("عرض تفاصيل المستفيد");
    var ill_manage = _("إدارة الطلب");
    var ill_manage_select_backend_first = _("حدد الواجهة الخلفية أولاً");
    var ill_all_statuses = _("كل الحالات");
    var ill_all_status_aliases = _("All status aliases");
    var ill_no_status_alias = _("No status alias");
    var ill_status_aliases = _("Status aliases");
</script>
<!-- / ill-list-table-strings.inc -->
