<!-- installer-strings.inc -->
<script>
    var MSG_LETTERS_ONLY=(_("يرجى إدخال حروف فقط."));
    var MSG_PASSWORD_MISMATCH=(_("كلمات المرور التي تم إدخالها غير متطابقة"));
    var MSG_ONE_ENROLLMENTPERIOD =(_("يرجى اختيار فترة التسجيل  بالشهور أو بواسطة التاريخ."));
    var MSG_ONLY_ONE_ENROLLMENTPERIOD=(_("يرجى اختيار فترة تسجيل واحدة فقط."));
    var MSG_LETTERS_NUMBERS_ONLY=(_("يرجى إدخال حروف أو ارقام فقط."));
</script>
<!-- / installer-strings.inc -->
