<div id="toolbar" class="btn-toolbar">
 <div class="btn-group">
 <button class="btn btn-default dropdown-toggle" data-toggle="dropdown"><i class="fa fa-plus"></i> جديد <span class="caret"></span></button>
 <ul class="dropdown-menu">
 <li><a href="/cgi-bin/koha/labels/label-edit-batch.pl?op=new">دفعة الملصقات</a></li>
 <li><a href="/cgi-bin/koha/labels/label-edit-layout.pl?op=new">التخطيط</a></li>
 <li><a href="/cgi-bin/koha/labels/label-edit-template.pl?op=new">قالب الملصق</a></li>
 <li><a href="/cgi-bin/koha/labels/label-edit-profile.pl?op=new">أوضاع الطابعة</a></li>
 <li><a href="/cgi-bin/koha/labels/label-edit-range.pl">نطاق الباركود</a></li>
 </ul>
 </div>
 <div class="btn-group">
 <button class="btn btn-default dropdown-toggle" data-toggle="dropdown"><i class="fa-solid fa-pencil" aria-hidden="true"></i> إدارة <span class="caret"></span></button>
 <ul class="dropdown-menu">
 <li><a href="/cgi-bin/koha/labels/label-manage.pl?label_element=batch">دفعات الملصقات</a></li>
 <li><a href="/cgi-bin/koha/labels/label-manage.pl?label_element=layout">التخطيطات</a></li>
 <li><a href="/cgi-bin/koha/labels/label-manage.pl?label_element=template">قوالب الملصق</a></li>
 <li><a href="/cgi-bin/koha/labels/label-manage.pl?label_element=profile">أوضاع الطابعة</a></li>
 </ul>
 </div>
</div>
