<div id="toolbar" class="btn-toolbar">
 <div class="btn-group">
 <button class="btn btn-default dropdown-toggle" data-toggle="dropdown"><i class="fa fa-plus"></i> جديد <span class="caret"></span></button>
 <ul class="dropdown-menu">
 <li><a href="/cgi-bin/koha/patroncards/edit-batch.pl?op=new">دفعة البطاقات</a></li>
 <li><a href="/cgi-bin/koha/patroncards/image-manage.pl">صورة</a></li>
 <li><a href="/cgi-bin/koha/patroncards/edit-layout.pl?op=new">التخطيط</a></li>
 <li><a href="/cgi-bin/koha/patroncards/edit-template.pl?op=new">قالب البطاقة</a></li>
 <li><a href="/cgi-bin/koha/patroncards/edit-profile.pl?op=new">أوضاع الطابعة</a></li>
 </ul>
 </div>
 <div class="btn-group">
 <button class="btn btn-default dropdown-toggle" data-toggle="dropdown"><i class="fa-solid fa-pencil" aria-hidden="true"></i> إدارة <span class="caret"></span></button>
 <ul class="dropdown-menu">
 <li><a href="/cgi-bin/koha/patroncards/manage.pl?card_element=batch">دفعة البطاقات</a></li>
 <li><a href="/cgi-bin/koha/patroncards/image-manage.pl">صور</a></li>
 <li><a href="/cgi-bin/koha/patroncards/manage.pl?card_element=layout">التخطيطات</a></li>
 <li><a href="/cgi-bin/koha/patroncards/manage.pl?card_element=template">قوالب البطاقة</a></li>
 <li><a href="/cgi-bin/koha/patroncards/manage.pl?card_element=profile">أوضاع الطابعة</a></li>
 </ul>
 </div>
</div>
